apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: twelvecloudbs
    app.kubernetes.io/name: twelvecloudbs
  name: twelvecloudbs
spec:
  storageClassName: "rook-nfs-share1"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi